# Generated by Django 3.2.13 on 2022-07-11 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nuit_applicatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_na', models.CharField(max_length=120, null=True)),
                ('Environnement_na', models.CharField(max_length=120, null=True)),
                ('Date_na', models.DateField()),
                ('Durée_na', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('moyenne_execution_na', models.DecimalField(decimal_places=2, max_digits=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Detail_na',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_job', models.CharField(max_length=120, null=True)),
                ('Date_heure_debut_na', models.DateTimeField()),
                ('Date_heure_fin_na', models.DateTimeField()),
                ('Statut_job', models.CharField(max_length=120, null=True)),
                ('nuit_applicatif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.nuit_applicatif')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_execution_job', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('detail_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.detail_na')),
            ],
        ),
    ]
